[package]
name = "adventofcrustacean"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "^0.10.0"
pathfinding = "0.1"
either = "1"
rand = "0.8"