name:                hadventofcode
version:             0.1.0.0
github:              "flavio-a/adventofcode"
license:             Unlicense
author:              "Flavio"
copyright:           "2020 Flavio"

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/flavio-a/adventofcode#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - array
    - mtl

executables:
  # day6:
  #   main: Day6.hs
  #   source-dirs: sols/day6
  #   dependencies:
  #     - hadventofcode
  #     - sort
  #
  # day7:
  #   main: Day7.hs
  #   source-dirs: sols/day7
  #   dependencies:
  #     - hadventofcode
  #     - split
  #
  # day8:
  #   main: Day8.hs
  #   source-dirs: sols/day8
  #   dependencies:
  #     - hadventofcode
  #     - extra
  #
  # day9:
  #   main: Day9.hs
  #   source-dirs: sols/day9
  #   dependencies:
  #     - hadventofcode
  #
  # day10:
  #   main: Day10.hs
  #   source-dirs: sols/day10
  #   dependencies:
  #     - hadventofcode
  #     - sort
  #
  # day11:
  #   main: Day11.hs
  #   source-dirs: sols/day11
  #   dependencies:
  #     - hadventofcode
  #     - array
  #     - split
  #
  # day12:
  #   main: Day12.hs
  #   source-dirs: sols/day12
  #   dependencies:
  #     - hadventofcode
  #     - array
  #     - extra

  day13:
    main: Day13.hs
    source-dirs: sols/day13
    dependencies:
      - hadventofcode
      - split
      - extra
      # - array

# tests:
#   hadventofcode-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - hadventofcode
