name:                monadventofcode
version:             0.1.0.0
github:              "flavio-a/adventofcode"
license:             Unlicense
author:              "Flavio"
# maintainer:          "example@example.com"
copyright:           "2021 Flavio"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/flavio-a/adventofcode#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - split
    - array
    - mtl
    - extra
    - monad-loops
    - containers
    - unordered-containers

executables:
  day2:
    main:                Main.hs
    source-dirs:         src/day2
    dependencies:
    - monadventofcode
  day5:
    main:                Main.hs
    source-dirs:         src/day5
    dependencies:
    - monadventofcode
  day7:
    main:                Main.hs
    source-dirs:         src/day7
    dependencies:
    - monadventofcode
  day9:
    main:                Main.hs
    source-dirs:         src/day9
    dependencies:
    - monadventofcode
  day11:
    main:                Main.hs
    source-dirs:         src/day11
    dependencies:
    - monadventofcode
    - unordered-containers
  day13:
    main:                Main.hs
    source-dirs:         src/day13
    dependencies:
    - monadventofcode
    - unordered-containers
    - monad-loops
  day15:
    main:                Main.hs
    source-dirs:         src/day15
    dependencies:
    - monadventofcode
    - containers
    - mtl
  day17:
    main:                Main.hs
    source-dirs:         src/day17
    dependencies:
    - monadventofcode
    - array


tests:
  monadventofcode-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - monadventofcode
